/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function readImageBuffer(path: string): Array<number>
/**
 * Creates a thumbnail from the provided image bytes with specified dimensions
 * Returns the thumbnail as a buffer of PNG-encoded bytes
 */
export declare function createThumbnailBuffer(imageBytes: Uint8Array, width: number, height: number): Array<number>
/** Saves the provided image buffer to a file at the specified path */
export declare function saveImageBuffer(imageBytes: Uint8Array, path: string): void
